# Generated by Django 4.1 on 2022-09-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TradingSupportApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyAnnouncements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("text", models.CharField(max_length=10)),
                ("link", models.CharField(max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TradingSupportApp.company",
                    ),
                ),
            ],
        ),
    ]
