# Generated by Django 4.0.3 on 2022-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingSupportApp', '0003_alter_announcements_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnwantedCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('wanted', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
