# Generated by Django 4.0.3 on 2022-08-10 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingSupportApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 10, 17, 3, 35, 884035)),
        ),
    ]
