# Generated by Django 4.0.3 on 2022-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingSupportApp', '0002_alter_announcements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(),
        ),
    ]
